version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on: 
      - db

  queue: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on: 
      - db
      
  db:
    image: mariadb:10.5.8
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306